# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: tap-gui-component
#   description: Tanzu Application Platform GUI Component
#   tags:
#     - v1alpha1
#   annotations:
#     'backstage.io/kubernetes-label-selector': 'app=backstage'
#     'backstage.io/techdocs-ref': dir:.
# spec:
#   type: service
#   lifecycle: production
#   owner: default-team
#   system: tap-gui

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-sensors
  description: spring-sensors Application
  tags:
    - java
    - spring
    - web
    - tanzu
  annotations:    
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-sensors'
    'backstage.tanzu.vmware.com/user.default.devuser1': 'catalog.entities.read'
spec:
  type: service
  lifecycle: experimental
  # owner: cloud-team
  owner: devops-team
  system: spring-sensors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-java-web-app
  description: Tanzu Java Web Application
  tags:
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=tanzu-java-web-app'
    # backstage.tanzu.vmware.com/<group|user>.<namespace>.<name>: 'COMMA-SEPARATED-PERMISSIONS'      
    'backstage.tanzu.vmware.com/user.default.clouduser1': 'catalog.entities.read' 
spec:
  type: service
  lifecycle: experimental
  owner: cloud-team
  system: tanzu-java-web-app
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-nodejs
  description: NodeJs Application
  tags:
    - java
    - nodejs
    - web
    - tanzu
  annotations:  
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=hello-nodejs'
    'backstage.tanzu.vmware.com/user.default.clouduser1': 'catalog.entities.read'   
spec:
  type: service
  lifecycle: experimental
  owner: cloud-team
  system: hello-nodejs
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jupyter-web-app
  description: jupyter-web-app Application
  tags:
    - java
    - spring
    - web
    - tanzu
  annotations:    
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=jupyter-web-app'
spec:
  type: service
  lifecycle: experimental
  # owner: cloud-team
  owner: devops-team
  system: jupyter-web-app