apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: devuser1
spec:
  profile:
    displayName: "Devops Team : devopsuser1"
    email: devuser1@vmware.com   # 이 부분이 OIDC email과 match 되어야 함
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [devops-team,api-group]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: clouduser1
spec:
  profile:
    displayName: "Cloud Team : clouduser1"
    email: clouduser1@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [cloud-team,api-group]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dha
spec:
  profile:
    displayName: Admin User
    email: dha@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [admin-group]   # admin 일 경우 별도 member를 넣지 않아도 됨
  # memberOf: [cloud-team,devops-team,api-group,admin-group]  
  
# ---
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: guest
# spec:
#   profile:
#     displayName: guest User
#     email: guest@example.com
#     picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
#   memberOf: [cloud-team]    
# ---
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: Devops User
# spec:
#   profile:
#     displayName: Workshop User
#     email: explore-workshop-s002@vmware.com
#     picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
#   memberOf: [devops-team]
